### ISSUE TITLE
2 Issues reports

### ISSUE THREAD

**Issue by cristianaghe** [Zomboided/service.vpn.manager.providers#46]
Hello,

We are facing some issues at the moment with using your project with the Cyberghost setup.
Some users are reporting issues when connecting to Kodi, as the ones attached.
![kodi_2020-05-05_17-02-31](https://user-images.githubusercontent.com/43184748/81268717-f925aa00-9050-11ea-9b15-f4413f75b139.png). Has this error been reported previously when using kodi VPN Manager by any chance?

Furthermore,another report is that the connection gets stuck at "checking location info" - from the project documentation that seems to mean the connection to a certain service used to determine location is being blocked - can you help us please understand the possible root cause of this error message and what should be done in order to enable its functionality?

Thank you!
Best regards,
Cristiana G.

**Comment by Zomboided** [comment]
Well let's be clear - the addon is just calling openvpn, so you can recreate this by using the command line.  The checking location info message is usually because the DNS is not working when the addon tries to call a service to see where it's located and what the external IP address is.  This is documented on the wiki in the Troubleshooting page.  I don't understand why some providers have this problem, and some don't.  THis also might be a problem for users across different distros.  I don't think this problem is as prevalent with LibreELEC, I think it's more of an issue with other distros.
